server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mldnmldn/spring-cloud-config      # 配置Git仓库的地址
          username:  yaojiaiteye@163.com                                                       # Git仓库的账号
          password:  yaojia123456                                                       # Git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/