server:
  port: 8000

security:
  basic:
    enabled: false
    
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                                  
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mldn
    username: root
    password: mysqladmin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.itmuch.cloud.study.entity
  mapper-locations:
  - classpath:mapper/*.xml
  
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG    #分布式跟踪 sleuth
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1